version: "3.8"
services:
  postgres:
    container_name: "messages-postgres"
    networks:
      - messages-network
    image: postgres:12
    restart: always
    environment:
      POSTGRES_DB: messages
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    command: postgres -c 'max_connections=500'
    volumes:
      - ./pg-data:/var/lib/postgresql/data
  nats:
    image: nats-streaming
    ports:
      - 8222:8222
      - 4222:4222
    networks:
      - messages-network

volumes:
  pg-data:

networks:
    messages-network:
